## YAML Template.
spring:
    datasource:
        url: jdbc:h2:mem:world_db
        username: sa
        password:
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
        database-platform: org.hibernate.dialect.H2Dialect